### PR TITLE
Bug: can't get the geolocation to work in CRA.

### PR DESCRIPTION
**Pull request by D-Pagey**
Please ignore the README updates, I probably shouldn't have included those in this branch. 

This is what I need Location.js to do:

1. Get my current position
2. Take that position and interpolate the latitude and longitude into a URL
3. Return that URL (which I can import into my App.js)

Through my trouble shooting - the `getCurrentPosition` API is flakely when using Create-React-App. I can't work out how to `return` the URL because `return finalUrl` doesn't seem to work. Or if it is working, I don't know how to get that into my App.js. When I use these exact functions on my native JS version on CodePen, it works every time.

### CODE REVIEW

**Comment by iammatthewward** [comment]
It looks like perhaps you are expecting to use `getUrl` to return a url like so:
```js
const myUrl = getUrl();
```
which won't work because the `geolocation.getCurrentPosition` API is asynchronous. If we take a look at the [API docs](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition), we can see that  `getCurrentPosition` expects to receive a success callback, and can also receive an error callback and an options object: `getCurrentPosition(success, error, options)`.

So in order to ever have the ability to do something similar to `const myUrl = getUrl();` we need to leverage Promises (and realistically, we'll want to use async/await). So first things first, lets create a new function to wrap the location API in a Promise:
```js
function getLocation() {
  return new Promise((resolve, reject) => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(resolve, reject);
    } else {
      reject('Geolocation not supported');
    }
  });
}
```
What we are doing here is creating and returning a new promise, which will allow us to either hook into the `then` function of `getLocation`, which will return the current position. Since the `getCurrentPosition` API expects a success and error callback, and Promises provide these exact callbacks with `resolve` and `reject`, we can just pass these along to `getCurrentPosition`, and they will get called at the appropriate time. Now we can use our new `getLocation` function in the function you are default exporting, `getUrl`:

```js
// instead of this:
if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
} else {
     alert("Geolocation not supported");
}

// we can do this:
getLocation().then(showPosition).then(url => {
    // this is the url we want
    console.log(url);
});
```

In fact what would be even nicer, is if we used async/await with this `getUrl` function so that we don't have to nest in order to access our URL. While we are at it, since we removed the alert in the case of an error, let's add error handling back in:
```js
export default async function getUrl() {
  const url = await getLocation().then(showPosition).catch(alert);
  // now we have access to the URL and can use it in fetch:
  fetch(url).then(...);
}
```
One final thing - you are currently declaring your `showPosition` function in the scope of the `getUrl` function, which is ok, but isn't necessary as you aren't leveraging closure in any way so these functions could quite happily exists side by side. In fact, by defining a function inside the scope of another function, you end up redefining the inner function each time the outer function is called, which isn't very performant. This is generally find where we need access to values from the closure, or if we are exporting a module function that is only called once, but in this instance it is probably best to define these functions side by side. So with that in mind, what we end up with is something like this:

```js
export default function getUrl() {
  return getLocation().then(showPosition).catch(alert);
}

function getLocation() {
  return new Promise((resolve, reject) => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(resolve, reject);
    } else {
      reject('Geolocation not supported');
    }
  });
}

function showPosition(position) {
  const lat = position.coords.latitude;
  const lon = position.coords.longitude;
  let finalUrl = "https://api.openweathermap.org/data/2.5/weather?lat=" +
    lat + "&lon=" + lon + "&appid=b8a569af62cc3d2b113f0b42813c6929&units=metric";
  return finalUrl;
}
```
This gives us a `getUrl` function we can import into a component. This function returns a promise which resolves to the URL, so we can use it like so:

```js
// inside a regular function
getUrl().then(url => {
  // do something with URL
});

// or inside an async function
const url = await getUrl();
```

**Comment by iammatthewward** [comment]
One final thing - `showPosition` in this instance probably does not have the most accurate name. What it is doing is using the position values to construct a URL, so I would probably rename it to `constructUrl`. We probably also want to be a bit more descriptive with the default export, so I would probably rename it to `getLocationUrl`

**Comment by D-Pagey** [comment]
First off thanks so much for taking the time to go into so much detail! 

I've pushed the latest version and having the same issue on both my Windows PC and Macbook. It seems that the `navigator.geoLocation` doesn't seem to be responding properly. 

error

**Comment by D-Pagey** [comment]
I guess a hacky solution would be to include the fetch in the Location.js? But that doesn't seem right, it smells.

**Comment by iammatthewward** [comment]
The problem is that you are importing `getUrl` and using it as a promise:
```js
getUrl().then(url => {
  fetch(url).then(...)
});
```
However you are not return a promise from the exported `getUrl` function. In fact, you are not returning _anything_:
```js
export default async function getUrl() {
  const url = await getLocation().then(constructUrl).catch(alert);
}
```
What you're doing here is calling the `getLocation` promise too early - calling it here will get you the URL you want, but you can never pass it higher up the chain (ie. it won't ever be accessible from the function that is invoking `getUrl`).

Since you want to have access to the URL returned from the `getUrl` promise in the same scope in which you invoke it, you need to pass the promise higher up the chain. Thankfully this is JavaScript, and we can pass promises around as much as we want. So all we need to do to fix this is change this:
```js
export default async function getUrl() {
  const url = await getLocation().then(constructUrl).catch(alert);
}
```
to this:
```js
export default function getUrl() {
  return getLocation().then(constructUrl).catch(alert);
}
```

**Comment by iammatthewward** [comment]
Also just for clarity around why you are getting the `Something went wrong` error, which appears to signal something is wrong with calling `navigator.geoLocation` (which is not the case):

you are not returning anything from `getUrl`, however it is an `async` function, which means it returns a promise (which will never resolve to anything, since you aren't returning anything). You are calling `fetch` with the return of `getUrl`, which since it is undefined, will result in `fetch` throwing an error. This is the error that is causing your `catch` statement to be called and log `Something went wrong`

This is an interesting quirk - the fact that `async` function returns a promise hides the fact you are not returning anything from `getUrl`, which it a little less obvious where the error originates

**Comment by D-Pagey** [comment]
You're a hero Matt, thanks!

**Pull request merged**
